<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Connexion_password-icon</name>
   <tag></tag>
   <elementGuidId>2487df20-651e-47e4-a78c-e34786f363c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='password-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3cadf63e-c8e4-484a-88ad-1094234a8cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>12685c7b-3b57-4db3-a41d-96a7a68aabe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-icon</value>
      <webElementGuid>5cfbe342-4b82-492e-b704-e2f2ff60b4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-icon&quot;)</value>
      <webElementGuid>71296d56-d33c-487c-935d-6e88693b95df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='password-icon']</value>
      <webElementGuid>cb6e5700-325f-4514-9c03-7930ae135887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/fieldset/div[2]/div/span/i</value>
      <webElementGuid>ea9c1573-359e-486a-9403-be2d338f75f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/i</value>
      <webElementGuid>515b0db0-05d6-4d1b-b530-62017c403985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'password-icon']</value>
      <webElementGuid>dbba638b-a088-4784-ad61-1937d375a7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
