<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connexion</name>
   <tag></tag>
   <elementGuidId>0721a18b-6600-4e7f-a75b-c0a51e647f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/fieldset/div[5]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb8a8295-317f-4176-bbf3-ff174c1aae33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigger-110 </value>
      <webElementGuid>daa6dc04-36bb-4a43-8e34-f6aa3c794deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>d6f37311-76c8-4e60-ae2f-4b29914f9d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/fieldset[1]/div[@class=&quot;clearfix&quot;]/button[@class=&quot;pull-right btn btn-sm btn-primary&quot;]/span[@class=&quot;bigger-110&quot;]</value>
      <webElementGuid>d82db425-4007-48e8-a893-b5d8573a4e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/fieldset/div[5]/button/span</value>
      <webElementGuid>26889aeb-2d25-4807-8c56-e833972e8fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connexion']/parent::*</value>
      <webElementGuid>63c4f4bf-3c9e-4f8e-949d-8b780ae98ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>e6e7efd3-77fd-4ff4-a37f-631cbda008c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>8ebb5881-1188-4627-b9cb-1126afebbc05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
