<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agenda</name>
   <tag></tag>
   <elementGuidId>1dc5405a-b47c-46c6-9088-0310ae99049e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborateur'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ak-menu-item.ng-tns-c3015560688-8.ng-star-inserted > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0dc33f1f-385d-4294-a30d-40a9e439199e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>59cf14e3-0ba4-4115-80d7-f11bc4dbef62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenda</value>
      <webElementGuid>f16bf4b8-7d8e-46f8-bff5-37885fb63234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-skin&quot;]/app-root[1]/ak-app-root[@class=&quot;ng-star-inserted&quot;]/ak-left-bar[1]/div[@class=&quot;sidebar responsive ak-layout-sidebar&quot;]/ak-menu[1]/ul[@class=&quot;nav nav-list&quot;]/ak-menu-group[@class=&quot;ng-tns-c3015560688-8 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c3015560688-8 active open&quot;]/ul[@class=&quot;submenu ng-tns-c3015560688-8 ng-trigger ng-trigger-focusMenu&quot;]/ak-menu-item[@class=&quot;ng-tns-c3015560688-8 ng-star-inserted&quot;]/li[1]/a[1]</value>
      <webElementGuid>b9427a15-099e-42c4-b3c5-37f0f937b8b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborateur'])[1]/following::a[1]</value>
      <webElementGuid>14a59183-fbb4-405f-ba12-09910792b624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon activité'])[1]/preceding::a[1]</value>
      <webElementGuid>52817e9c-8490-4446-99aa-f2de41a64ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>97296e1a-1670-462d-b0c6-4401d4a0372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ak-menu-item/li/a</value>
      <webElementGuid>012c1f63-1840-4f3d-aee6-82f59e1f89b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Agenda' or . = 'Agenda')]</value>
      <webElementGuid>0bd44b33-f0cc-4d43-a1eb-10a008629d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
