<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notes de frais</name>
   <tag></tag>
   <elementGuidId>16e0c45f-8fd0-4daf-b654-bbad43d53c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Notes de frais')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.expense-reports.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0561b4eb-350d-4af9-9f1f-53c571ab71c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>./</value>
      <webElementGuid>fa1ae548-c452-4ab5-8751-47f47adb1460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>a7cbd7df-365f-4f46-8fad-881b4a16442b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expense-reports active</value>
      <webElementGuid>7e00fe0c-6a27-4f10-b5b8-03cf7e5e4e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/employees/expenses</value>
      <webElementGuid>354b3a01-3eb7-46bd-9d23-7141892c64fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Notes de frais </value>
      <webElementGuid>8ec1958b-24da-4c97-b751-8cdabb1de38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-skin&quot;]/app-root[1]/ak-app-root[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content bg-white&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/h2[1]/a[@class=&quot;expense-reports active&quot;]</value>
      <webElementGuid>636a0a5e-059e-4923-8cd2-1b28a632e371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Notes de frais')])[2]</value>
      <webElementGuid>1b6078d3-c20b-4786-b6f8-0f3273a922c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Déconnexion'])[1]/following::a[1]</value>
      <webElementGuid>4c10af0c-c9bc-4e30-ae8a-90c833d40608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aide'])[1]/following::a[2]</value>
      <webElementGuid>3bbfa79d-29e6-4a1b-9b5a-5c35ba99fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Dépense'])[1]/preceding::a[1]</value>
      <webElementGuid>856c62ba-1a00-4143-afa8-35a510df966d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout replier'])[1]/preceding::a[1]</value>
      <webElementGuid>16f7d387-6c83-47db-8e33-0ac43458739b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/employees/expenses')])[2]</value>
      <webElementGuid>7abf118a-9c75-499b-b110-a99a69e68a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>521e6782-08c3-4b6c-9a48-a6c665cbe1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/employees/expenses' and (text() = ' Notes de frais ' or . = ' Notes de frais ')]</value>
      <webElementGuid>f2388eb6-152c-47d4-b4ce-272380e738a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
