<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agenda</name>
   <tag></tag>
   <elementGuidId>6cf2fd15-98df-4fa9-bd3c-a4d1db65ebaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='akuiteo-breadcrumb']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa2f0d8e-3487-4d1a-8e30-d92f6796f6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenda</value>
      <webElementGuid>943bc922-15b0-4ddf-bf96-9f1091fb4b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;akuiteo-breadcrumb&quot;)/div[@class=&quot;akuiteo-breadcrumb-container&quot;]/div[@class=&quot;akuiteo-breadcrumb-entry&quot;]/a[1]</value>
      <webElementGuid>e04be21d-110a-4e08-846f-36acca6512ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='akuiteo-breadcrumb']/div/div[2]/a</value>
      <webElementGuid>a3680cac-4773-4926-8c52-ee08b04756d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agenda')]</value>
      <webElementGuid>5f7c1664-62eb-4cc3-9051-4781a3ad38d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborateur'])[2]/following::a[1]</value>
      <webElementGuid>90dd6bd6-57fa-4d2c-a8dc-6815fbacc502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barre Latérale'])[1]/following::a[2]</value>
      <webElementGuid>5fb4afcb-b9a5-4619-92a2-3c66b68e9b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dorian Hill'])[1]/preceding::a[1]</value>
      <webElementGuid>6aeba792-6fa1-47b7-a6a3-3e7f8bab288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Société Sud'])[1]/preceding::a[1]</value>
      <webElementGuid>0943c29d-4cc6-4bb9-81d8-88e205b2a516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6c87fcba-0fc7-432b-9a8d-c3119a62fb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Agenda' or . = 'Agenda')]</value>
      <webElementGuid>06e48171-6fa8-45d6-a6a9-de96621a9111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
