<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fermer</name>
   <tag></tag>
   <elementGuidId>705dcad2-a792-4738-bd11-622d916a16c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendarEventFormCloseModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendarEventFormCloseModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e58bf928-2cbe-4673-8cbb-0c4a686314c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarEventFormCloseModal</value>
      <webElementGuid>a65ebded-c231-4580-a725-2199b08d51d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>85181342-5b85-4db4-a318-f1ffab3a9d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>8427ac33-3a90-4a45-a916-02c5eb172868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fermer</value>
      <webElementGuid>82387700-02b7-4ae0-987f-3b0574f7cc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarEventFormCloseModal&quot;)</value>
      <webElementGuid>4a4bf035-a2ea-46c6-9be5-62e9eb8d5351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calendarEventFormCloseModal']</value>
      <webElementGuid>35dc0036-daab-4e9e-a0ae-59e6df2d7ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calendarEventForm']/div[2]/a</value>
      <webElementGuid>008cce5f-f76c-49e7-9290-adcb08bb3dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fermer')]</value>
      <webElementGuid>52fa4e40-066c-4535-b2f8-2cbe0716053c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réunion visio'])[1]/following::a[1]</value>
      <webElementGuid>3d963b08-d974-4772-bf52-46973d87e1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Termine à midi'])[1]/following::a[1]</value>
      <webElementGuid>24883e52-c2e2-4fcf-822a-d55b416b01c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/preceding::a[1]</value>
      <webElementGuid>b8243c43-fdb1-4127-9922-757c528cc8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fermer']/parent::*</value>
      <webElementGuid>7f5fd16c-3af0-4b5d-8e9c-d2c75478af1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>ba570ff8-5108-443e-b70c-e2cdb7080442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calendarEventFormCloseModal' and (text() = 'Fermer' or . = 'Fermer')]</value>
      <webElementGuid>3b57a962-d919-4840-8830-2d8145cf60df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
