<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crer</name>
   <tag></tag>
   <elementGuidId>d5d4708c-cd3c-4bfb-9172-277ad2e2e66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cda11a5c-be31-463f-bf5b-1d6bedb688b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-btn</value>
      <webElementGuid>88df7418-9a86-4e14-8bbb-962140fea3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btnLeft</value>
      <webElementGuid>0df2e94c-d3f0-4073-8995-218f7345a22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				
				Créer
			</value>
      <webElementGuid>c158262e-0559-4aa0-b28f-191ad0889f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-btn&quot;)</value>
      <webElementGuid>f269d0df-17c2-4aa4-ade4-3a239313ea98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-btn']</value>
      <webElementGuid>59338d14-a5b0-419e-a779-d9a1867b694c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-actions']/div/button</value>
      <webElementGuid>1aa1a3a7-4aea-4053-8570-a2e3bec73b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::button[1]</value>
      <webElementGuid>df53e4b7-478e-4f8a-99e5-7d73ff59b3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Déconnexion'])[1]/following::button[1]</value>
      <webElementGuid>39a48432-28dc-46b6-ba6c-629054277157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dupliquer semaine (temps)'])[1]/preceding::button[1]</value>
      <webElementGuid>8e714b08-eeb0-4839-b5cd-e7657e32cb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>88e3793e-5f5d-42a1-86e9-fe33f3110078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'create-btn' and (text() = '
				
				Créer
			' or . = '
				
				Créer
			')]</value>
      <webElementGuid>920b29cc-33af-4309-8c8d-bf7d78f1f635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
