<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>67a6dc55-1483-4235-8bcd-bd304b6cae2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blocDuree']/div[2]/div/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>61290c5a-5712-4378-acb9-864d5b220578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>e11d5d20-bc67-4067-a7db-7e25f0ebf887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>afc7470e-2749-4044-ba6d-3f5283ae8d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blocDuree&quot;)/div[@class=&quot;col-xs-6&quot;]/div[@class=&quot;knob-container inline&quot;]/div[1]/div[1]/canvas[1]</value>
      <webElementGuid>3d3ec438-2348-4c2e-89e1-60c79f5f74a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocDuree']/div[2]/div/div/div/canvas</value>
      <webElementGuid>7eab6f24-4d92-4dc0-ba80-354d2ffa3a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>5eafe02d-9b22-4566-89eb-254f518370c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
