<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dplacement (DPMNT)</name>
   <tag></tag>
   <elementGuidId>642b7bbb-c988-4cf8-9acc-b5d2ac876cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='1']/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1 > td > div.quickfield-ellipsis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a388051c-1611-4036-ab0f-9d26aeb7351f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickfield-ellipsis</value>
      <webElementGuid>d82b07ce-a480-4ed2-b0dd-89d3805409b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Déplacement (DPMNT)</value>
      <webElementGuid>7416b288-9a5a-42a3-a050-32ede8f0b1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Déplacement (DPMNT)</value>
      <webElementGuid>2e4a6fe4-bc48-4697-9636-6ad0cce0c6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/td[1]/div[@class=&quot;quickfield-ellipsis&quot;]</value>
      <webElementGuid>855d7b1b-7359-4643-945b-78840d79d675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td/div</value>
      <webElementGuid>6eefd41c-8588-4cf8-8b16-cbdccf545fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absence (ABS)'])[1]/following::div[1]</value>
      <webElementGuid>fc15eb58-2535-4d34-9dcc-a9e36baf1517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::div[3]</value>
      <webElementGuid>f9d7ccb5-3636-481e-932c-adf4c5637fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travail (TRVL)'])[1]/preceding::div[1]</value>
      <webElementGuid>9341b1c7-1f3d-4cb3-a4ec-7d3272f7a10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Déplacement (DPMNT)']/parent::*</value>
      <webElementGuid>172a1b43-c103-4260-998d-080b043ab3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div</value>
      <webElementGuid>03f69c81-d581-4422-9d98-9f31e2625f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Déplacement (DPMNT)' and (text() = 'Déplacement (DPMNT)' or . = 'Déplacement (DPMNT)')]</value>
      <webElementGuid>5af45838-fd6b-4c4e-9ef8-b416ddd036fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absence'])[1]/following::div[1]</value>
      <webElementGuid>95f94ba0-32e7-44bb-9310-74e95f6d7882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
