<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Optimal Compta  5h00Tche de test 06Absence</name>
   <tag></tag>
   <elementGuidId>2d3ed932-803a-46e9-a8e8-f2e78f7d6158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-1']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.event_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40e2bebe-0244-4f97-8814-2a4165df938f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>event_description</value>
      <webElementGuid>d8030bd3-a291-4b8c-b339-2b76ab327262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Optimal Compta / 5h00Tâche de test 06Absence</value>
      <webElementGuid>6526ece5-b8b0-4b6b-a9e0-9f67705cdedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-1&quot;)/div[@class=&quot;fc-content&quot;]/div[@class=&quot;event_description&quot;]</value>
      <webElementGuid>dc7e5703-348e-44f0-bd47-e1557f11f5e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-id-1']/div/div[2]</value>
      <webElementGuid>d30f44ad-6f11-47be-b284-3acedf8a354d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optimal Compta'])[1]/following::div[1]</value>
      <webElementGuid>e128dec0-12cf-4dbc-ad4f-afa248d4315e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dim. 13'])[1]/following::div[18]</value>
      <webElementGuid>24ccbf3a-4cc1-4256-a0d1-3113df278219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div[2]</value>
      <webElementGuid>ac2f708c-4f14-4986-a334-68e04bde459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Optimal Compta / 5h00Tâche de test 06Absence' or . = 'Optimal Compta / 5h00Tâche de test 06Absence')]</value>
      <webElementGuid>f5f3abfd-6a7c-478d-b569-b7aab26edb0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
