<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Runion visio_blocDuree</name>
   <tag></tag>
   <elementGuidId>7d52e379-e5b5-4650-8dbc-d72eba5c08a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blocDuree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#blocDuree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1a0450b-159b-4cfb-8421-6944270e32ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ak:persotype</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>a6c06335-7ca6-4855-a6cd-3a5d8efeaafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ak:persocomment</name>
      <type>Main</type>
      <value>Durée</value>
      <webElementGuid>d91477b4-9ac2-41c8-bba5-25cc2dedbb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blocDuree</value>
      <webElementGuid>cd5d173a-27e2-44ba-9dd3-da333d50e4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group</value>
      <webElementGuid>ac30c0b8-81dc-4609-8241-6c775d4e89da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blocDuree&quot;)</value>
      <webElementGuid>557e544f-1c20-4a07-a8a8-5dbaf33a7f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='blocDuree']</value>
      <webElementGuid>85704e4d-9e1c-4cc7-b2bc-667e86df0842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calendarEventForm']/div/div[2]/div[9]</value>
      <webElementGuid>37074532-4621-439a-bed8-b6dcc5054758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réunion visio'])[1]/following::div[24]</value>
      <webElementGuid>70a1c58b-4292-42fd-babe-97aa45bb2a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Termine à midi'])[1]/following::div[30]</value>
      <webElementGuid>d3583ef9-bc31-4f5a-bcb2-5d51e4f14c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/preceding::div[16]</value>
      <webElementGuid>887b7aa5-f703-41d3-ae7c-8c16e0e0c6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/preceding::div[16]</value>
      <webElementGuid>0f54faae-25e9-4675-bb56-83cd39412731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[9]</value>
      <webElementGuid>3b13510a-0e48-4dd9-b085-027dbdead015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'blocDuree']</value>
      <webElementGuid>5d269a67-57e5-4a7e-b430-af9a7a68f0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
