<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CHESSY  Optimal Compta  9 impasse du but</name>
   <tag></tag>
   <elementGuidId>b0281d0d-d0a5-44f3-aca5-6428bb9c29af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='0']/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.quickfield-ellipsis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0b66741-c7e3-4eab-b071-8e23de26500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickfield-ellipsis</value>
      <webElementGuid>f1e2164f-2c94-425c-bebd-f10c8a4e9165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>CHESSY / Optimal Compta / 9 impasse du but</value>
      <webElementGuid>b6dd273b-176b-4623-a954-a8019836ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHESSY / Optimal Compta / 9 impasse du but</value>
      <webElementGuid>3dc3583a-2e5b-4f0f-9f3c-c18a519cfcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/td[1]/div[@class=&quot;quickfield-ellipsis&quot;]</value>
      <webElementGuid>e83cb2e6-76e9-4e1c-acc4-3a25e3e187dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='0']/td/div</value>
      <webElementGuid>8081caa1-75b9-4a01-8814-65a970ee434c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lieu'])[1]/following::div[2]</value>
      <webElementGuid>4710fcab-b16a-4314-8e25-c09c2b115d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::div[5]</value>
      <webElementGuid>92a6ddaf-fb09-4f1d-a3fd-887309cb1990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BORDEAUX / Optimal Compta // Optimal Compta Sud Ouest / 33 montée de la mer'])[1]/preceding::div[1]</value>
      <webElementGuid>c5225507-a219-4022-895f-be449fd4fa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHESSY / Optimal Compta / 9 impasse du but']/parent::*</value>
      <webElementGuid>e2fc37a8-3b2c-414c-8273-459a43623184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>3e9161d2-7fd6-416a-808a-2c2671e374ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'CHESSY / Optimal Compta / 9 impasse du but' and (text() = 'CHESSY / Optimal Compta / 9 impasse du but' or . = 'CHESSY / Optimal Compta / 9 impasse du but')]</value>
      <webElementGuid>9b3398ba-6ba7-44c1-82fc-9fd2200f04af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/ Optimal Compta / 9 impasse du but']/parent::*</value>
      <webElementGuid>96ef5d7f-3e57-4c19-a730-c08ce3130b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
