<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_S32  Du 7  au 13 aot 2023</name>
   <tag></tag>
   <elementGuidId>5905bbe0-6632-4d07-81bb-9dc97ce98c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fullcalendar']/div/div[3]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cb4e736e-96d3-4cd9-b32b-d1b1e7a0050e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S32 : Du 7  au 13 août 2023</value>
      <webElementGuid>fd17c58d-29c7-4c41-ab34-e86138ef5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullcalendar&quot;)/div[@class=&quot;fc-toolbar fc-header-toolbar&quot;]/div[@class=&quot;fc-center&quot;]/h2[1]</value>
      <webElementGuid>b43d7466-9c9d-452b-94e7-c409a8060f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullcalendar']/div/div[3]/h2</value>
      <webElementGuid>93a49747-204e-4d02-be07-2e55d2d8f198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jour'])[1]/following::h2[1]</value>
      <webElementGuid>a3ec022c-4ba5-407d-8391-616c2055d094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semaine'])[1]/following::h2[1]</value>
      <webElementGuid>153ab3fe-b0d0-4499-87e3-cf76bdeb7c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lun. 7'])[1]/preceding::h2[1]</value>
      <webElementGuid>fdeea3a3-15c5-4034-b34d-4febbe3db417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mar. 8'])[1]/preceding::h2[1]</value>
      <webElementGuid>82595aed-d4b5-4486-b66c-521450489b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>a079a645-8cf9-44b2-a769-bf7f69fbeed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'S32 : Du 7  au 13 août 2023' or . = 'S32 : Du 7  au 13 août 2023')]</value>
      <webElementGuid>15c2278b-622a-4865-9ad9-b242f6f62735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
