<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Action</name>
   <tag></tag>
   <elementGuidId>c5a39944-1530-405c-bb47-a46936353188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover979839']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.popover-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ab626124-be53-42f2-bdd5-a073d708a339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-title</value>
      <webElementGuid>0c4dda9c-86b4-4a59-9298-142dfc4674e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>6bb27bac-e720-47d1-abea-82bb2d5cbb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover979839&quot;)/h3[@class=&quot;popover-title&quot;]</value>
      <webElementGuid>f585bd36-5d5b-4de6-a57e-1e1f74ee6ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover979839']/h3</value>
      <webElementGuid>a1ebd49f-bf42-45b7-a196-57836fdb572c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::h3[1]</value>
      <webElementGuid>6a5bc294-9f3e-4421-a0da-aad19ccd23bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::h3[1]</value>
      <webElementGuid>787f145c-7d72-47dc-9621-ef5795872327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absence (ABS)'])[1]/preceding::h3[1]</value>
      <webElementGuid>94ee4a6c-6a55-4def-a42c-30aa239c7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Déplacement (DPMNT)'])[1]/preceding::h3[1]</value>
      <webElementGuid>a66944c8-1310-45fe-b487-902787706639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Action']/parent::*</value>
      <webElementGuid>6c322b77-b213-4aeb-b915-e68b2862d236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>08172d2b-b5f4-43ac-aba3-3cb837ea866e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Action' or . = 'Action')]</value>
      <webElementGuid>3fae02ff-47e8-4af6-ab43-c3209c1c90ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover634006']/h3</value>
      <webElementGuid>57e438a3-eb87-44e7-94c4-291bcc7f15fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
