<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Affaires</name>
   <tag></tag>
   <elementGuidId>973370a1-1b68-46c0-9395-39ffd5d15461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover876228']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.popover-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>072b0c64-064f-44ba-8d06-363ce9be8254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-title</value>
      <webElementGuid>6064afeb-5b3f-44dc-baef-99d02469c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Affaires</value>
      <webElementGuid>1b113829-00d4-4725-8876-889f0eab9c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover876228&quot;)/h3[@class=&quot;popover-title&quot;]</value>
      <webElementGuid>231432a0-358c-40e6-a0a3-e154a877e334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover876228']/h3</value>
      <webElementGuid>1376dac8-8c0a-4044-8de5-3a923f3371e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::h3[1]</value>
      <webElementGuid>da2edc5c-c5e1-48f5-b198-22432917432f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::h3[1]</value>
      <webElementGuid>f93d49cf-e3c3-4c05-8df5-07036d674c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archi Tendance (ARCHI-TEND)'])[1]/preceding::h3[1]</value>
      <webElementGuid>60161458-01d3-4494-a209-ee1a6d95b46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coopérative FNC (COOP-FNC)'])[1]/preceding::h3[1]</value>
      <webElementGuid>99b9bb52-3a44-40d6-8045-60eb4d577969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Affaires']/parent::*</value>
      <webElementGuid>6c80638e-74f0-4346-a17d-acc3a144a573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>63fc6d9c-b512-4e4e-a6df-3a89797db2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Affaires' or . = 'Affaires')]</value>
      <webElementGuid>19ea7d95-3307-4423-b6a1-195f8a2c04a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover934872']/h3</value>
      <webElementGuid>b0afd540-ac96-43ef-bd9a-293fb4bfe768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover311954']/h3</value>
      <webElementGuid>318102e0-6e74-47f4-a7b6-83cba072fe32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optimal Compta (OPTI-COMPT)'])[1]/preceding::h3[1]</value>
      <webElementGuid>3fe46682-742f-4db8-a56e-c03377245e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sud (SUD)'])[1]/preceding::h3[1]</value>
      <webElementGuid>492dc05f-2500-4d93-9838-9441482aa1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
