<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Lieu</name>
   <tag></tag>
   <elementGuidId>12e85259-56cb-4107-bafe-91d3b32dfd84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover817613']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.popover-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>22b0a360-ecd8-4b36-bfab-dffdc1fdda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-title</value>
      <webElementGuid>96711053-1e17-45ef-b5f5-3db3b56bf34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lieu</value>
      <webElementGuid>29e75077-bbf0-4387-a020-9c758d7819d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover817613&quot;)/h3[@class=&quot;popover-title&quot;]</value>
      <webElementGuid>e04f046e-5f44-478a-8bbf-3c56634333eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover817613']/h3</value>
      <webElementGuid>b6af3d66-faea-4f4a-afe8-6ba62bfb3bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::h3[1]</value>
      <webElementGuid>5bdf949a-e26e-43c2-9935-9501cd6bf79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::h3[1]</value>
      <webElementGuid>ca2ecedd-9f33-40f9-83ec-0dfaff6505ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHESSY / Optimal Compta / 9 impasse du but'])[1]/preceding::h3[1]</value>
      <webElementGuid>c7009fdb-c827-4cbc-91b2-9b0d679b4332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BORDEAUX / Optimal Compta // Optimal Compta Sud Ouest / 33 montée de la mer'])[1]/preceding::h3[1]</value>
      <webElementGuid>a452469c-d583-4fca-a3ec-66214893fd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lieu']/parent::*</value>
      <webElementGuid>8294ccf2-0fa6-40a8-a775-0b3cf1a3d51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>b2598346-c036-4411-bd3c-731e48766b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Lieu' or . = 'Lieu')]</value>
      <webElementGuid>c72cead8-3f5c-4a29-be9a-4c9f0f812964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
