<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Tche</name>
   <tag></tag>
   <elementGuidId>b85cfbeb-ced4-48c8-b458-cb9fc2c70f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover797066']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.popover-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>93b894ac-61ad-4420-8604-e2a8b3165c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-title</value>
      <webElementGuid>d15f226b-542d-4d6b-9052-a30b4da1b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tâche</value>
      <webElementGuid>9d1cfc11-f468-48bf-b16b-678959386dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover797066&quot;)/h3[@class=&quot;popover-title&quot;]</value>
      <webElementGuid>22eb68f3-b4b3-4cc3-bff9-6b2d2f9ff57d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover797066']/h3</value>
      <webElementGuid>979cd76b-89c5-40a9-a63a-65ff7cfd0c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::h3[1]</value>
      <webElementGuid>3a3c7619-0765-4f0b-83dd-760668e340d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::h3[1]</value>
      <webElementGuid>31676f75-8276-4a75-beb9-3d1e954044d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tâche de test 06'])[1]/preceding::h3[1]</value>
      <webElementGuid>debe1234-fb50-4c75-a662-cdf7642fefaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tâche']/parent::*</value>
      <webElementGuid>6dc1c1a2-25e2-4655-a418-60b793ca5d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>00fa024e-66e5-472f-9534-b9c37e3f22d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Tâche' or . = 'Tâche')]</value>
      <webElementGuid>9764c3b0-0d68-4d5c-a4d6-aabea763dafc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
