<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Runion visio_nomAction</name>
   <tag></tag>
   <elementGuidId>be81ee9a-a566-48ec-9be0-9a8d51128025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nomAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8997d55-ff48-4058-858f-cacf15ec9ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ak-off</value>
      <webElementGuid>36282bf8-11ac-42f2-96b8-15141a25d39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13dffbd1-3867-48c1-9e16-24c319bc99b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm quickfield-input</value>
      <webElementGuid>c1a69cf9-71a7-47dd-af1f-d70c2a852e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomAction</value>
      <webElementGuid>fd315056-cd96-4fd5-9d40-54cf45fa6e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomAction</value>
      <webElementGuid>4aab9c85-b2c7-49e5-8c49-2ee8ce7df0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>e44108a9-2f61-44f8-adcb-25bf6ea6c1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomAction&quot;)</value>
      <webElementGuid>f849f3b7-0f02-42f9-9370-67cf8fadafa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomAction']</value>
      <webElementGuid>de384ac4-6358-4b6a-bd29-e70e77172d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calendarEventForm']/div/div[2]/div[8]/div/div/input[2]</value>
      <webElementGuid>3a862869-016d-4517-89cf-fe71db01b761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input[2]</value>
      <webElementGuid>38585afe-b4fe-4978-a787-800c24d72e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nomAction' and @name = 'nomAction' and @placeholder = 'Action']</value>
      <webElementGuid>9ee57973-31fa-49e6-a810-43a4568caeef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
