<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Runion visio_dureeHelper</name>
   <tag></tag>
   <elementGuidId>72e164d2-0921-4ea7-9038-2589425457b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dureeHelper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dureeHelper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e012af4-dce6-4635-8876-9a6a7ed2eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dureeHelper</value>
      <webElementGuid>120acfc3-ef4a-48e0-a40f-14f067ad2892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7ddd05c2-f7a3-4388-9382-03dff7f4a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45682863-a73b-4b20-b728-259879518a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small knob</value>
      <webElementGuid>898ff85e-ff4a-4942-af74-f40d4ef97d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f437064e-13d6-45e1-ac28-c217244196de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>f92a24c1-f6ae-4204-8b6c-a45412c13eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-height</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>44fa4660-6841-4ee0-91e7-4529e6d64e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thickness</name>
      <type>Main</type>
      <value>.3</value>
      <webElementGuid>ff87c4e3-83d8-488d-912d-7116fa8fa86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dureeHelper&quot;)</value>
      <webElementGuid>72cac751-0578-4525-843d-f55a2c9301a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dureeHelper']</value>
      <webElementGuid>d5f763b0-9c57-4aaf-8783-6ec455d433ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocDuree']/div[2]/div/div/div/input</value>
      <webElementGuid>c78d3aa8-94e6-45c1-8257-eb479e001cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/div/input</value>
      <webElementGuid>1108b1ad-1cf2-4780-944c-b520e10f1779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dureeHelper' and @type = 'text']</value>
      <webElementGuid>26285cd3-0833-413a-a923-0c395179703f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
