<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Runion visio_nomAffaire</name>
   <tag></tag>
   <elementGuidId>5544e558-5e72-4290-8044-9b44e390061a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomAffaire']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nomAffaire</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21847412-36f3-4e2a-ae5c-a446a261130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86bcb545-732a-4ba7-b399-472560e5f069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm quickfield-input</value>
      <webElementGuid>32461a21-06a6-4b40-badd-89661e8d8a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomAffaire</value>
      <webElementGuid>52809b7a-4ac8-45e9-b6f2-020928b3108b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomAffaire</value>
      <webElementGuid>595808ee-a242-402d-8e5a-fde706a6a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ak-off</value>
      <webElementGuid>73bb7fd8-efed-4ce8-bee8-d356ddc5148c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Affaire</value>
      <webElementGuid>d54ca607-4369-4868-b91f-9d4048475316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover866894</value>
      <webElementGuid>5a87aa91-a0e7-44fd-8943-a85382158061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomAffaire&quot;)</value>
      <webElementGuid>96943f51-a891-4d35-919c-5d4c5f7e6e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Optimal Compta</value>
      <webElementGuid>23b645d9-3002-4481-b42e-b1642c1f1006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomAffaire']</value>
      <webElementGuid>39579646-0788-4135-86d0-fd742b97c2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calendarEventForm']/div/div[2]/div[7]/div[2]/div/div/input</value>
      <webElementGuid>e8482217-3e0c-4ba1-a3e3-9647e7cd5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>4d2c4d15-78ba-4802-a661-c1ab8e86ec35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nomAffaire' and @name = 'nomAffaire' and @placeholder = 'Affaire']</value>
      <webElementGuid>25994d67-4598-44b8-8d4b-59e88a9c0cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
