<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Runion visio_duree</name>
   <tag></tag>
   <elementGuidId>de8bc0de-5f0e-41f9-9242-757831d1439e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='duree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#duree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22034940-c1bb-4480-9436-542132a3d4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9776c3e9-2f82-4194-9057-d7f0a53d614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm text-right</value>
      <webElementGuid>43db4796-9cb6-4354-b243-ab8285a97a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duree</value>
      <webElementGuid>fde02fcc-2954-4d77-81d6-a16ed49c48ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>duree</value>
      <webElementGuid>37b1373e-c062-4e15-bde7-8a49a41e16cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Durée</value>
      <webElementGuid>844dfdd6-5926-40ae-8147-9dc2cefa6ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duree&quot;)</value>
      <webElementGuid>48aaaaf2-ab8d-47fb-b452-b6aa495e7bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='duree']</value>
      <webElementGuid>7cfe61fa-8da6-4395-9417-aa705dafabb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blocDuree']/div/div/input</value>
      <webElementGuid>3b1e867d-6a7a-4eaa-be28-781738c2822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/input</value>
      <webElementGuid>8d052e74-df29-44be-b17b-292088e6bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'duree' and @name = 'duree' and @placeholder = 'Durée']</value>
      <webElementGuid>8b5711f9-c230-4ac5-b43f-be1feecf1919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
