<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Runion visio_libelleTache</name>
   <tag></tag>
   <elementGuidId>a5be3f6d-bb04-4759-8ea1-533dd4454407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='libelleTache']//input[@id='libelleTache']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#libelleTache</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d957dfac-a55b-42d5-9907-5c11b4427361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cef85f2-cb5d-49fb-a4ee-5b93b0144cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm quickfield-input</value>
      <webElementGuid>f07ec605-36ea-4cb5-9b62-036b31bccc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>libelleTache</value>
      <webElementGuid>e0f5bc94-77f3-41ca-aa9b-0d2853977164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>libelleTache</value>
      <webElementGuid>6705b9d7-0a39-4f04-95e8-382a4e13666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tâche</value>
      <webElementGuid>9fca6cb7-e74b-4902-a65d-6a9d217ac1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;libelleTache&quot;)</value>
      <webElementGuid>a0c38629-8493-4ad6-87ab-e1e49c0cc53d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='libelleTache']</value>
      <webElementGuid>eb589543-c9bc-462b-abe8-31c82b6e08cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calendarEventForm']/div/div[2]/div[7]/div[5]/div[2]/div/input</value>
      <webElementGuid>a1b81c36-970e-466e-9ecd-6d60451385b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>09ea99ab-b338-43b2-a138-92ced06db5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'libelleTache' and @name = 'libelleTache' and @placeholder = 'Tâche']</value>
      <webElementGuid>b7237549-5bcf-46b9-bfce-2a3b90dde8b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
