<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Tche de test 06</name>
   <tag></tag>
   <elementGuidId>40bfcc88-7d45-4a60-a38c-f3748927e5af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='0']/td/div/mark</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>7aa3177f-96e6-4cfb-b9cf-4931841f7896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tâche de test 06</value>
      <webElementGuid>7354dc28-9a12-4984-b602-4101cc6c00b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/td[1]/div[@class=&quot;quickfield-ellipsis&quot;]/mark[1]</value>
      <webElementGuid>408d2e0d-459c-4f98-9c13-ef220bb0c778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='0']/td/div/mark</value>
      <webElementGuid>a3722641-8903-4854-a910-e614a21a095f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tâche'])[1]/following::mark[1]</value>
      <webElementGuid>9147fce2-fccb-48a5-86af-84f968f4bf36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::mark[1]</value>
      <webElementGuid>0c56cba0-9fd9-4bf1-8f59-158bb0073b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>651f959b-bb91-4771-99d7-2d8da9c47a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Tâche de test 06' or . = 'Tâche de test 06')]</value>
      <webElementGuid>a968d5ba-d0e8-4558-b704-058d1ee1516a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
